
insert into FLIGHT(FLIGHT_NUMBER, ORIGIN, DESTINATION, DEPARTURE_TIME, ARRIVAL_TIME,FARE) values('A101', 'AMS', 'DEL', '11:00', '17:00','800');
insert into FLIGHT(FLIGHT_NUMBER, ORIGIN, DESTINATION, DEPARTURE_TIME, ARRIVAL_TIME,FARE) values('B101', 'AMS', 'BOM', '12:00', '19:00','750');
insert into FLIGHT(FLIGHT_NUMBER, ORIGIN, DESTINATION, DEPARTURE_TIME, ARRIVAL_TIME,FARE) values('C101', 'AMS', 'BLR', '13:00', '18:30','800');
insert into FLIGHT(FLIGHT_NUMBER, ORIGIN, DESTINATION, DEPARTURE_TIME, ARRIVAL_TIME,FARE) values('B102', 'AMS', 'BOM', '14:00', '21:30','900');
insert into FLIGHT(FLIGHT_NUMBER, ORIGIN, DESTINATION, DEPARTURE_TIME, ARRIVAL_TIME,FARE) values('C102', 'AMS', 'BLR', '12:00', '18:00','850');
insert into FLIGHT(FLIGHT_NUMBER, ORIGIN, DESTINATION, DEPARTURE_TIME, ARRIVAL_TIME,FARE) values('C103', 'AMS', 'BLR', '10:30', '17:00','730');
insert into FLIGHT(FLIGHT_NUMBER, ORIGIN, DESTINATION, DEPARTURE_TIME, ARRIVAL_TIME,FARE) values('D101', 'AMS', 'MAA', '09:00', '15:00','600');
insert into FLIGHT(FLIGHT_NUMBER, ORIGIN, DESTINATION, DEPARTURE_TIME, ARRIVAL_TIME,FARE) values('E101', 'MAA', 'BOM', '08:00', '18:00','800');
insert into FLIGHT(FLIGHT_NUMBER, ORIGIN, DESTINATION, DEPARTURE_TIME, ARRIVAL_TIME,FARE) values('G101', 'BOM', 'DEL', '06:00', '12:00','850');
insert into FLIGHT(FLIGHT_NUMBER, ORIGIN, DESTINATION, DEPARTURE_TIME, ARRIVAL_TIME,FARE) values('A201', 'LHR', 'DEL', '18:00', '19:30','100');
insert into FLIGHT(FLIGHT_NUMBER, ORIGIN, DESTINATION, DEPARTURE_TIME, ARRIVAL_TIME,FARE) values('B201', 'LHR', 'BOM', '12:35', '19:30','600');
insert into FLIGHT(FLIGHT_NUMBER, ORIGIN, DESTINATION, DEPARTURE_TIME, ARRIVAL_TIME,FARE) values('C201', 'LHR', 'BLR', '13:45', '16:30','800');
insert into FLIGHT(FLIGHT_NUMBER, ORIGIN, DESTINATION, DEPARTURE_TIME, ARRIVAL_TIME,FARE) values('D201', 'LHR', 'MAA', '09:45', '15:30','600');